Ignore access time difference in tests
Special care is required to preserve file access time
and not disturb it later. Unsure if it is of any practical use.

Failure example:

    FAIL: test_symlink_deep (test_app_actions.TestCopy) (i='atime')
    Copy symlink entities with referenced directory content.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/scrapbook-src/PyWebScrapBook-dev/test/test_app_actions.py", line 183, in assert_file_equal
        self.assertAlmostEqual(stat0[i], stati[i], delta=2)
    AssertionError: 1600400850.1926882 != 31536000.0 within 2 delta (1568864850.1926882 difference)